app = 'badge-forge'
primary_region = 'cdg'

[build]
dockerfile = 'Dockerfile'

[env]
PORT = '4000'
WORKER_COUNT = '1'

[http_service]
internal_port = 4000
force_https = true
auto_stop_machines = 'off'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[vm]]
memory = '256mb'
cpu_kind = 'shared'
cpus = 1

[[metrics]]
port = 9091
path = '/metrics'
